version: "3.8"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    hostname: db
    platform: linux/amd64

  app:
    build: ./app
    ports:
      - 8888:8888
    depends_on:
      - db
    environment:
      DB_HOST: db

